### ISSUE TITLE
在wayland下执行python3 manage.py -h报错

### ISSUE THREAD

**Issue by DarkLii** [linuxdeepin/deepin-autotest-framework#52]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/Xlib/xauth.py", line 43, in __init__
    raw = open(filename, 'rb').read()
FileNotFoundError: [Errno 2] 没有那个文件或目录: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 574, in <module>
    Manage()
  File "manage.py", line 144, in __init__
    from src.depends.cfonts import say
  File "/tmp/pycharm_project_743/src/__init__.py", line 21, in <module>
    from src.assert_common import AssertCommon as AssertCommon
  File "/tmp/pycharm_project_743/src/assert_common.py", line 20, in <module>
    from src.dogtail_utils import DogtailUtils
  File "/tmp/pycharm_project_743/src/dogtail_utils.py", line 30, in <module>
    from src.mouse_key import MouseKey
  File "/tmp/pycharm_project_743/src/mouse_key.py", line 35, in <module>
    from src.depends.pyautogui import _pyautogui_wayland as pyautogui
  File "/tmp/pycharm_project_743/src/depends/pyautogui/__init__.py", line 250, in <module>
    import mouseinfo
  File "/usr/local/lib/python3.7/dist-packages/mouseinfo/__init__.py", line 223, in <module>
    _display = Display(os.environ['DISPLAY'])
  File "/usr/local/lib/python3.7/dist-packages/Xlib/display.py", line 80, in __init__
    self.display = _BaseDisplay(display)
  File "/usr/local/lib/python3.7/dist-packages/Xlib/display.py", line 62, in __init__
    display.Display.__init__(*(self, ) + args, **keys)
  File "/usr/local/lib/python3.7/dist-packages/Xlib/protocol/display.py", line 61, in __init__
    name, host, displayno)
  File "/usr/local/lib/python3.7/dist-packages/Xlib/support/connect.py", line 91, in get_auth
    return mod.get_auth(sock, dname, host, dno)
  File "/usr/local/lib/python3.7/dist-packages/Xlib/support/unix_connect.py", line 103, in new_get_auth
    au = xauth.Xauthority()
  File "/usr/local/lib/python3.7/dist-packages/Xlib/xauth.py", line 45, in __init__
    raise error.XauthError('~/.Xauthority: %s' % err)
Xlib.error.XauthError: ~/.Xauthority: [Errno 2] 没有那个文件或目录: ''

**Comment by mikigo** [comment]
UOS 1070 Wayland下 XAUTHORITY 环境变量有问题，在框架里面添加此环境变量
